// Mocks generated by Mockito 5.4.6 from annotations
// in unihub/test/services/chat_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:unihub/core/services/ai_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatSession_0 extends _i1.SmartFake implements _i2.ChatSession {
  _FakeChatSession_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAIClient_1 extends _i1.SmartFake implements _i2.AIClient {
  _FakeAIClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIClient extends _i1.Mock implements _i2.AIClient {
  MockAIClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get defaultSystemInstruction => (super.noSuchMethod(
        Invocation.getter(#defaultSystemInstruction),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#defaultSystemInstruction),
        ),
      ) as String);

  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
      ) as bool);

  @override
  _i2.ChatSession startChat({List<Map<String, dynamic>>? history}) =>
      (super.noSuchMethod(
        Invocation.method(
          #startChat,
          [],
          {#history: history},
        ),
        returnValue: _FakeChatSession_0(
          this,
          Invocation.method(
            #startChat,
            [],
            {#history: history},
          ),
        ),
      ) as _i2.ChatSession);

  @override
  _i4.Future<String> generateContent(
    String? prompt, {
    String? base64Image,
    String? mimeType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateContent,
          [prompt],
          {
            #base64Image: base64Image,
            #mimeType: mimeType,
          },
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateContent,
            [prompt],
            {
              #base64Image: base64Image,
              #mimeType: mimeType,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateContentFromMessages(
          List<Map<String, dynamic>>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateContentFromMessages,
          [messages],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #generateContentFromMessages,
            [messages],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [ChatSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatSession extends _i1.Mock implements _i2.ChatSession {
  MockChatSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AIClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeAIClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.AIClient);

  @override
  String get systemInstruction => (super.noSuchMethod(
        Invocation.getter(#systemInstruction),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#systemInstruction),
        ),
      ) as String);

  @override
  _i4.Future<String> sendMessage(
    String? text, {
    String? base64Image,
    String? mimeType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [text],
          {
            #base64Image: base64Image,
            #mimeType: mimeType,
          },
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #sendMessage,
            [text],
            {
              #base64Image: base64Image,
              #mimeType: mimeType,
            },
          ),
        )),
      ) as _i4.Future<String>);
}
